# This configuration is intended for development purposes only
version: '3.8'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    # volumes:
    #   - ~/volumes/apps/turbo-umbrella/mongodb/:/data/db/
